### ISSUE TITLE
Question, how do I add and query 3d points in this octree?

### ISSUE THREAD

**Issue by trsh** [SilvanCodes/tpntree#1]

**Comment by SilvanCodes** [comment]
Hey trsh,

it's not a use case I've implemented so far, but it'll make a great addition.
I'll do it this weekend and come back to you!

**Comment by SilvanCodes** [comment]
Checkout:
https://github.com/SilvanCodes/tpntree/commit/42ce6c582e7ff63ebefc8f62cd8ed1a2d06aa09b#diff-b62202585b9d407f910b13ae86c99b1387365bd7f697980a04372d5cf508313f
and https://docs.rs/tpntree once it has been build!

**Comment by trsh** [comment]
Cool tnx. Will check out soon.
